version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - FLASK_DEBUG=1
      - PYTHONPATH=.
    env_file:
      - .env
    command: python app.py
    restart: unless-stopped