version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test:
    docker:
      - image: cimg/node:20.18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Playwright browsers with dependencies
          command: npx playwright install --with-deps
      - run:
          name: Run tests
          command: npm test

workflows:
  test-workflow:
    jobs:
      - test
