name: Docker Build & Push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        load: true
        tags: path-app:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create test environment
      run: |
        docker run -d --name path-test \
          -p 8000:8000 \
          -e GEMINI_API_KEY=test-key \
          -e FLASK_DEBUG=1 \
          path-app:test
        docker ps

    - name: Wait for app to start
      run: |
        echo "Waiting for app to start..."
        sleep 10
        docker logs path-test
        timeout 60 bash -c 'until curl -f http://localhost:8000/ > /dev/null 2>&1; do
          echo "Waiting..."; sleep 3;
        done' || {
          echo "App failed to start, checking logs:"
          docker logs path-test
          exit 1
        }

    - name: Run health check
      run: |
        echo "Testing app endpoints..."
        echo "Root endpoint:"
        curl -s http://localhost:8000/ | head -20
        echo -e "\n\nVerify endpoint:"
        if curl -s http://localhost:8000/verify | grep -q "verification"; then
          echo "✅ App is responding correctly"
        else
          echo "❌ App not responding as expected"
          echo "Response content:"
          curl -s http://localhost:8000/verify | head -20
          docker logs path-test
          exit 1
        fi

    - name: Clean up
      run: |
        docker stop path-test || true
        docker rm path-test || true
