name: Docker Build & Push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        load: true
        tags: path-app:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create test environment
      run: |
        docker run -d --name path-test \
          -p 8000:8000 \
          -e GEMINI_API_KEY=test-key \
          -e FLASK_DEBUG=1 \
          path-app:test
        docker ps

    - name: Wait for app to start
      run: |
        timeout 30 bash -c 'until curl -f http://localhost:8000/verify; do sleep 2; done' || true

    - name: Run health check
      run: |
        if curl -s http://localhost:8000/verify | grep -q "verification"; then
          echo "✅ App is responding"
        else
          echo "❌ App not responding"
          exit 1
        fi

    - name: Clean up
      run: |
        docker stop path-test || true
        docker rm path-test || true
