name: End-to-End Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'e2e/**'
      - 'app.py'
      - 'templates/**'
      - 'static/**'
      - 'tests/**'
      - 'playwright.config.js'
  pull_request:
    branches: [ main ]
    paths:
      - 'e2e/**'
      - 'app.py'
      - 'templates/**'
      - 'static/**'
      - 'tests/**'
      - 'playwright.config.js'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Increased timeout for E2E tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install Playwright
      run: |
        npm install -D @playwright/test
        npx playwright install --with-deps chromium
        
    - name: Run Flask server
      run: |
        export FLASK_APP=app.py
        export FLASK_ENV=production
        nohup python -m flask run --port=8000 --no-debugger --no-reload > server.log 2>&1 &
        echo "Waiting for server to start..."
        sleep 5
        curl -v http://localhost:8000 || true
        
    - name: Run E2E tests
      run: |
        npx playwright test --config=playwright.config.js --workers=1
      env:
        BASE_URL: http://localhost:8000
        CI: true
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
        retention-days: 7
        
    - name: Upload server logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: server-logs
        path: server.log
        retention-days: 7
        
    - name: Show server logs on error
      if: failure()
      run: |
        echo "=== Server Logs ==="
        cat server.log || true
        
        echo "=== Test Results ==="
        find test-results -type f -name "*.txt" -exec echo "=== {} ===" \; -exec cat {} \; || true
